# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_factorial <- function(n) {
    .Call(`_lamle_rcpp_factorial`, n)
}

find_row <- function(cand_mat, pool_mat) {
    .Call(`_lamle_find_row`, cand_mat, pool_mat)
}

FindUniqComb_jlmr_GLLVM <- function(loadmat, check_zero) {
    .Call(`_lamle_FindUniqComb_jlmr_GLLVM`, loadmat, check_zero)
}

FindUniqComb_jlmrst_GLLVM <- function(loadmat, check_zero) {
    .Call(`_lamle_FindUniqComb_jlmrst_GLLVM`, loadmat, check_zero)
}

gi <- function(z, apars, bpars, modeltype, mi, y) {
    .Call(`_lamle_gi`, z, apars, bpars, modeltype, mi, y)
}

dgidz <- function(z, apars, bpars, modeltype, probs, mi, p, y) {
    .Call(`_lamle_dgidz`, z, apars, bpars, modeltype, probs, mi, p, y)
}

optC <- function(start, tol, maxit, y, J, cats, p, model, modelpars, modeltype, link, estimator, mu, invSigma) {
    .Call(`_lamle_optC`, start, tol, maxit, y, J, cats, p, model, modelpars, modeltype, link, estimator, mu, invSigma)
}

infoC <- function(start, tol, maxit, y, J, cats, p, model, modelpars, modeltype, link, estimator, information, mu, invSigma) {
    .Call(`_lamle_infoC`, start, tol, maxit, y, J, cats, p, model, modelpars, modeltype, link, estimator, information, mu, invSigma)
}

hoptC <- function(theta, y, J, cats, p, model, modelpars, modeltype, link, mu, Sigma) {
    .Call(`_lamle_hoptC`, theta, y, J, cats, p, model, modelpars, modeltype, link, mu, Sigma)
}

dhoptC <- function(theta, y, J, cats, p, model, modelpars, modeltype, link, mu, Sigma) {
    .Call(`_lamle_dhoptC`, theta, y, J, cats, p, model, modelpars, modeltype, link, mu, Sigma)
}

mleoptC <- function(theta, y, J, cats, p, model, modelpars, modeltype, link) {
    .Call(`_lamle_mleoptC`, theta, y, J, cats, p, model, modelpars, modeltype, link)
}

dmleoptC <- function(theta, y, J, cats, p, model, modelpars, modeltype, link) {
    .Call(`_lamle_dmleoptC`, theta, y, J, cats, p, model, modelpars, modeltype, link)
}

dhdb <- function(theta, sigma, betamat, x, ndim, nind) {
    .Call(`_lamle_dhdb`, theta, sigma, betamat, x, ndim, nind)
}

d2hdtdb <- function(theta, sigma, betamat, x, ndim, nind) {
    .Call(`_lamle_d2hdtdb`, theta, sigma, betamat, x, ndim, nind)
}

d2gidz2 <- function(z, apars, bpars, modeltype, probs, dprobs, mi, p, y) {
    .Call(`_lamle_d2gidz2`, z, apars, bpars, modeltype, probs, dprobs, mi, p, y)
}

dgidu <- function(z, apars, bpars, modeltype, probs, mi, p, y) {
    .Call(`_lamle_dgidu`, z, apars, bpars, modeltype, probs, mi, p, y)
}

d2gidzdu <- function(z, apars, bpars, modeltype, probs, dprobs, dprobsdu, mi, p, y) {
    .Call(`_lamle_d2gidzdu`, z, apars, bpars, modeltype, probs, dprobs, dprobsdu, mi, p, y)
}

gj_GRM_probit <- function(ynj, theta, apars, bpars, mj) {
    .Call(`_lamle_gj_GRM_probit`, ynj, theta, apars, bpars, mj)
}

dgjdu_GRM_probit <- function(ynj, theta, dpnorm1, dpnorm2, mj, pj, nparj) {
    .Call(`_lamle_dgjdu_GRM_probit`, ynj, theta, dpnorm1, dpnorm2, mj, pj, nparj)
}

dgjdt_GRM_probit <- function(apars, dpnorm1, dpnorm2, pj) {
    .Call(`_lamle_dgjdt_GRM_probit`, apars, dpnorm1, dpnorm2, pj)
}

d2gjd2t_GRM_probit <- function(ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj) {
    .Call(`_lamle_d2gjd2t_GRM_probit`, ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj)
}

d3gjd3t_GRM_probit <- function(ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj) {
    .Call(`_lamle_d3gjd3t_GRM_probit`, ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj)
}

d4gjd4t_GRM_probit <- function(ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj) {
    .Call(`_lamle_d4gjd4t_GRM_probit`, ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj)
}

d5gjd5t_GRM_probit <- function(ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj) {
    .Call(`_lamle_d5gjd5t_GRM_probit`, ynj, apars, linpred1, linpred2, dpnorm1, dpnorm2, mj, pj)
}

item_GRM <- function(ynj, thetajj, aparsjj, bparsjj, link, mj_jj, pj, nparj) {
    .Call(`_lamle_item_GRM`, ynj, thetajj, aparsjj, bparsjj, link, mj_jj, pj, nparj)
}

item_GRM_quad <- function(ynj, thetajj, aparsjj, bparsjj, link, mj_jj, pj, nparj) {
    .Call(`_lamle_item_GRM_quad`, ynj, thetajj, aparsjj, bparsjj, link, mj_jj, pj, nparj)
}

item_GRM_3rd <- function(ynj, thetajj, aparsjj, bparsjj, link, mj_jj, pj, nparj, Pi, dt2du) {
    .Call(`_lamle_item_GRM_3rd`, ynj, thetajj, aparsjj, bparsjj, link, mj_jj, pj, nparj, Pi, dt2du)
}

tabletolist <- function(estfixpars, J, mi, model, modeltype, G) {
    .Call(`_lamle_tabletolist`, estfixpars, J, mi, model, modeltype, G)
}

mglogLGrad <- function(pars, estfixpars, y, theta, J, mi, p, model, modeltype, link, N, covstruct, G, group, filters, X, approx, accuracy, npartype) {
    .Call(`_lamle_mglogLGrad`, pars, estfixpars, y, theta, J, mi, p, model, modeltype, link, N, covstruct, G, group, filters, X, approx, accuracy, npartype)
}

chol_deri <- function(mat_in) {
    .Call(`_lamle_chol_deri`, mat_in)
}

mglogLGrad_quad <- function(pars, estfixpars, y, theta, J, mi, p, model, modeltype, link, N, covstruct, G, group, filters, X, adapt, fullexp, quadp, quadw, method, npartype) {
    .Call(`_lamle_mglogLGrad_quad`, pars, estfixpars, y, theta, J, mi, p, model, modeltype, link, N, covstruct, G, group, filters, X, adapt, fullexp, quadp, quadw, method, npartype)
}

